spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret.key=7Iqk7YyM66W07YOA7L2U65Sp7YO065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67Cp7J6F64uI64uk7ISc7KO866qF7Iqk7YOA66W07YOA65287YOA7Iqk7YOA65+9